blank_issues_enabled: true
contact_links:
  - name: ðŸ’¡ Feature request
    url: https://lnk.earth/dsctickets-feedback
    about: Suggest a new feature on Feedbacky
  - name: ðŸ‘‹ Discussions
    url: https://github.com/discord-tickets/bot/discussions
    about: Start a discussion to ask for help or anything else
